version: "3.9"

services:

  redis:
    image: redis:6.2.11-bullseye
    container_name: redis
    hostname: redis
    restart: unless-stopped
    stop_grace_period: 10s
    ports:
      - 6379:6379
